/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms.View;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lms.Controller.BorrowReturnController;
import lms.Dto.BorrowReturnDto;

/**
 *
 * @author ASUS
 */
public class BorrowReturnView extends javax.swing.JFrame {
    
    private final BorrowReturnController BORROWRETURN_CONTROLLER;
    /**
     * Creates new form ReturnView
     */
    public BorrowReturnView() {
        BORROWRETURN_CONTROLLER = new BorrowReturnController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brwid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        duedate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        brwdate = new javax.swing.JTextField();
        retdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        brwtable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        fine = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BORROW RETURN VIEW");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 282, 56));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Borrow ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 110, 134, -1));
        getContentPane().add(brwid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 229, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 248, 125, -1));
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 248, 229, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Return Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 289, 125, -1));
        getContentPane().add(brwdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 229, -1));
        getContentPane().add(retdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 289, 229, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fine");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 323, 125, -1));

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 110, -1, -1));

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 151, -1, -1));

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 190, -1, -1));

        brwtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Borrow ID", "Book ID", "Member ID", "Borrow Date", "Due Date", "Return Date", "Fine"
            }
        ));
        brwtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brwtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(brwtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 379, 603, 245));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Borrow Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 216, 125, -1));

        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 229, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member ID ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 182, 125, 16));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, 134, -1));

        bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidActionPerformed(evt);
            }
        });
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 141, 229, -1));
        getContentPane().add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 229, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 248, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/View/rm218-bb-07.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
    updateBorrow();
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
     saveBorrow();
    }//GEN-LAST:event_savebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       deleteBorrow();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void brwtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brwtableMouseClicked
       searchBorrow();
    }//GEN-LAST:event_brwtableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainMenuView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowReturnView().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField brwdate;
    private javax.swing.JTextField brwid;
    private javax.swing.JTable brwtable;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField duedate;
    private javax.swing.JTextField fine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField retdate;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables


    

    
            


public void clearForm() {
        brwid.setText("");
        bid.setText("");
        mid.setText("");
        brwdate.setText("");
        duedate.setText("");
        retdate.setText("");
        fine.setText("");
    }

 private void loadTable() {
        try {
            String[] columns = {"Borrow ID", "Book ID", "Member ID", "Borrow Date", "Due Date", "Return Date", "Fine"};
            DefaultTableModel borrowtable = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            brwtable.setModel(borrowtable);

            ArrayList<BorrowReturnDto> borrowreturnDtos = BORROWRETURN_CONTROLLER.getAll();
            for (BorrowReturnDto borrowreturnDto : borrowreturnDtos) {
                Object[] rowData = {borrowreturnDto.getBorrowId(),
                    borrowreturnDto.getBookId(), borrowreturnDto.getMemberId(), borrowreturnDto.getBorrowDate(), borrowreturnDto.getDueDate(),
                borrowreturnDto.getReturnDate(), borrowreturnDto.getFine()};
                borrowtable.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

private void saveBorrow() {
    try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Date borrowDate = dateFormat.parse(brwdate.getText());
        Date dueDate = dateFormat.parse(duedate.getText());

        BorrowReturnDto dto = new BorrowReturnDto(
            brwid.getText(),
            bid.getText(),
            mid.getText(),
            borrowDate,
            dueDate
        );

        String resp = BORROWRETURN_CONTROLLER.save(dto);
        JOptionPane.showMessageDialog(this, resp);
        loadTable();
        clearForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


private void searchBorrow() {
    try {
        int selectedRow = brwtable.getSelectedRow();
        if (selectedRow != -1) {
            String id = (String) brwtable.getValueAt(selectedRow, 0);
            BorrowReturnDto dto = BORROWRETURN_CONTROLLER.get(id);

            if (dto != null) {
                brwid.setText(dto.getBorrowId());
                bid.setText(dto.getBookId());
                mid.setText(dto.getMemberId());
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                if (dto.getBorrowDate() != null) {
                    brwdate.setText(dateFormat.format(dto.getBorrowDate()));
                } else {
                    brwdate.setText("");
                }
                if (dto.getDueDate() != null) {
                    duedate.setText(dateFormat.format(dto.getDueDate()));
                } else {
                    duedate.setText("");
                }
                if (dto.getReturnDate() != null) {
                    retdate.setText(dateFormat.format(dto.getReturnDate()));
                } else {
                    retdate.setText("");
                }
                fine.setText(Double.toString(dto.getFine()));
            } else {
                JOptionPane.showMessageDialog(this, "Borrow not found");
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

 private void deleteBorrow() {
     
     
        try {
            String resp = BORROWRETURN_CONTROLLER.delete(brwid.getText());
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }


  private void updateBorrow() {
      
      
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
              Date borrowDate = dateFormat.parse(brwdate.getText());
                 Date dueDate = dateFormat.parse(duedate.getText());
                 Date returnDate = dateFormat.parse(retdate.getText());
        
                String borrowDateString = dateFormat.format(borrowDate);
                String dueDateString = dateFormat.format(dueDate);
                String returnDateString = dateFormat.format(returnDate);
                
            BorrowReturnDto dto = new BorrowReturnDto(
            brwid.getText(),
            bid.getText(),
            mid.getText(),
            borrowDate,
            dueDate,
            returnDate,
            Double.valueOf(fine.getText())
        );
            String resp = BORROWRETURN_CONTROLLER.update(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }






}
